import React from 'react'; 
import { LoginFooter } from './LoginFooter'; 

export default {
    title: 'CompositeComponents/LoginFooter',
    component: LoginFooter
}

const Template = (args) => <LoginFooter {...args} />; 

export const ADefault = Template.bind({}); 
ADefault.args = {
    description: 'This HIPAA-compliant website was automatically generated by your healthcare provider to offer you useful information and savings on your medications.',
    linkOne: 'Privacy',
    linkTwo: 'Terms'
};
